---
title: "Final project EDA"
author: "Clay Olsen"
output:
  pdf_document: default
  html_notebook: default
---
```{r}
##create data partition
library("caret")
library("grpreg")
library(caTools)
set.seed(123)

data(birthwt.grpreg)
noGroup <- c(1:16)
group <- c(1,1,1,2,2,2,3,3,4,5,5,6,7,8,8,8)
#split into test and train sets
sample = sample.split(birthwt.grpreg$bwt, SplitRatio = 0.75)
train <- subset(birthwt.grpreg, sample== TRUE)
test <- subset(birthwt.grpreg, sample == FALSE)

lm_baby <- lm(bwt~age1 + age2 + age3 + lwt1 + lwt2 + lwt3 + white + black + smoke + ptl1 + ptl2m +ht + ui + ftv1 + ftv2, data = train)
par(mfrow = c(1,2))

X <- as.matrix(train[,-1:-2])
y <- train$bwt
X_test <- as.matrix(test[,-1:-2])
Y_test <- test$bwt
str(birthwt.grpreg)
```

#Normal Lasso

```{r}
set.seed(123)
cvfit <- cv.grpreg(X, y, noGroup)
plot(cvfit)
summary(cvfit)
c_las <- coef(cvfit) ## Beta at minimum CVE
c_las
```

```{r}
##makes plot to show change in B by change in lambda with lasso
fit2 <- grpreg(X, y, noGroup, penalty="grLasso")

myColors <- c("black","black","black","red","red", "red", "green","cyan", "blue", "purple", "purple","yellow","orange", "brown","brown","brown")
labs <- c("Mother's Age","Mother's Age2","Mother's Age3", "Mother's weight","Mother's weight","Mother's weight" ,"White","Black", "Smoking","Premature1","Premature2", "Hypertension", "Uterine irritability", "# Phys. visits1","# Phys. visits2","# Phys. visits3")
plot(fit2, legend.loc="topleft", lwd=2, legend=labs, col = myColors, main = "Lasso")

abline(v = 0.0818)
```


#Grouped Lasso

```{r}
#######
set.seed(123)
cvfit2 <- cv.grpreg(X, y, group)
plot(cvfit2)
summary(cvfit2)
coef(cvfit2) ## Beta at minimum CVE
```

```{r}
##makes plot to show change in B by change in Lambda with Lasso

fit <- grpreg(X, y, group, penalty="grLasso")

myColors <- c("black", "red", "green", "blue", "yellow", "purple",
              "orange", "brown")
labs <- c("Mother's Age", "Mother's weight", "Race", "Smoking",
          "# Premature", "Hypertension", "Uterine irritability", "# Phys. visits")
plot(fit, legend.loc="topleft", lwd=2, alpha=0.5, legend=labs,col=myColors, main = "Group Lasso")

abline(v = 0.0679)
```



#GRLARS

```{r}
#install.packages("robustHD")
set.seed(123)
library(robustHD)
library(lars)
fit_lar <- grplars(X,y, group = group)
fit_lar


```
```{r}
par(mfrow = c(2,1))
critPlot(fit_lar, main = "Group LARS")
plot(fit_lar, main = "Group LARS")
```


#Group NNG

```{r}
set.seed(123)

cvfit3 <- cv.grpreg(X, y, group=group,penalty = "grSCAD", seed = 123)
summary(cvfit3)
coef(cvfit3)
```


```{r}
set.seed(123)

nng_fit <- grpreg(X,y,group, penalty= "grSCAD")
plot(nng_fit, legend.loc="topleft", lwd=2, alpha=1, legend=labs,col=myColors, main = "Group NNG")

abline(v = 0.0679)
```




###Predictions
```{r}
set.seed(123)

prediction_las <- sum(predict(cvfit,X_test,lambda = 0.0299))
prediction_grlas <- sum(predict(cvfit2,X_test,lambda = 0.0272))
predict_grlars <- sum(predict(fit_lar,X_test))
predict_grNNG <- sum(predict(cvfit3, X_test))


#plot(prediction1,y, xlab = "Predicted Weight Group Lasso", ylab = "Actual Weight")
#plot(prediction2,y, xlab = "Predicted Weight Lasso", ylab = "Actual Weight")
prediction_las
prediction_grlas
predict_grlars
predict_grNNG
```

```{r}
set.seed(123)

#install.packages("stargazer")
library(stargazer)
pred_models <- data.frame(c("prediction_las", "prediction_grlas", "predict_grlars", "predict_grNNG"), c(prediction_las, prediction_grlas, predict_grlars, predict_grNNG))
names(pred_models)[1] <- "methods"
names(pred_models)[2] <- "Prediction error"
pred_models

```































